branches:
  only:
    - master
    - /^\d+\.\d+\.\d+-\d+$/
sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 20.0
script: "rebar3 eunit"
after_success:
  - VERSION=`cat VERSION`
    if [ `git rev-list ${VERSION}.0 2>/dev/null` ]; then
      VERSION=${VERSION}.`git rev-list --merges --count ${VERSION}.0`;
    else
      VERSION=${VERSION}.0
    fi

    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        echo "Attempting to tag new release";
        git config --global user.email "builds@travis-ci.com";
        git config --global user.name "Travis CI";
        
        git tag ${VERSION} -a -m "Generated tag from TravisCI build ${TRAVIS_BUILD_NUMBER}";
        git push --quiet https://${GIT_KEY}@github.com/aufishgrp/istype ${VERSION} > /dev/null 2>&1;
      elif [ "${TRAVIS_TAG}" ]; then
        echo "Attempting to tag new release";
        mkdir -p ~/.hex;
        echo '{username,<<"'${HEX_USERNAME}'">>}.' > ~/.hex/hex.config;
        echo '{key,<<"'${HEX_KEY}'">>}.' >> ~/.hex/hex.config;

        mkdir -p ~/.config/rebar3;
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config;

        printf "y\n" | rebar3 hex publish;
      fi
    fi
