sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 20.0
script: "rebar3 eunit"
after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        mkdir -p ~/.hex;
        echo '{username,<<"'${HEX_USERNAME}'">>}.' > ~/.hex/hex.config;
        echo '{key,<<"'${HEX_KEY}'">>}.' >> ~/.hex/hex.config;

        mkdir -p ~/.config/rebar3;
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config;

        printf "y\n" | rebar3 hex publish;
      fi
    fi
