language: erlang
otp_release:
  - 20.0
sudo: required
notifications:
  email: false
install:
  - sudo apt-get install -y httpie
  - git clone https://github.com/inaka/elvis.git ~/Git/elvis;
    cd ~/Git/elvis;
    rebar3 escriptize;
    sudo cp _build/default/bin/elvis /usr/bin/elvis
  - cd ${TRAVIS_BUILD_DIR}
script:
  - elvis rock
  - rebar3 eunit
after_success:
  - scripts/travis.sh
