sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 20.0
script: "rebar3 eunit"
after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        echo "Attempting to tag new release";
        git config --global user.email "builds@travis-ci.com";
        git config --global user.name "Travis CI";
        export GIT_TAG=`cat VERSION`.`git rev-list --all --merges --count`;
        echo "Using version ${GIT_TAG}";
        git tag ${GIT_TAG} -a -m "Generated tag from TravisCI build ${TRAVIS_BUILD_NUMBER}";
        git push https://${GIT_KEY}@github.com/aufishgrp/istype ${GIT_TAG};
      elif [ "${TRAVIS_TAG}" ]; then
        echo "Attempting to push to hex";
        mkdir -p ~/.hex;
        echo '{username,<<"'${HEX_USERNAME}'">>}.' > ~/.hex/hex.config;
        echo '{key,<<"'${HEX_KEY}'">>}.' >> ~/.hex/hex.config;

        mkdir -p ~/.config/rebar3;
        echo '{plugins, [rebar3_hex]}.' > ~/.config/rebar3/rebar.config;

        printf "y\n" | rebar3 hex publish;
      fi
    fi
